### ISSUE TITLE
Response codes

### ISSUE THREAD

**Issue by evilive3000** [checkout/checkout-sdk-node#129]
There is no code in response body. I checked the code and there are no ways to get this through the sdk.
Can you add codes to the body so I could log and produce more informative error description for the users?

I'm talking of this https://docs.checkout.com/testing/response-code-testing

**Comment by evilive3000** [comment]
Props `response_code` & `response_summary` located in different places for different requests.
For non 3ds card they can be found in the root of response's body.
For 3ds with `capture: false` these props are inside array `.actions: [{...}]`
When payment requested with `capture: true` these properties are absent.

**Comment by ioan-ghisoi-cko** [comment]
This is not an issue with the SDK. This is an API behaviour.

For reference, in a non-3DS payment, you get the response code in the body since the response represents the authorisation outcome. For a *Get Payment* request after 3ds authentication, you can the response codes for each action since they could be different. For example, a payment could be authorised, but the capture can fail.

For further clarifications please reach out to integration@checkout.com
